services:
  mongo:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: taskdb
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/taskdb --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: laravel-backend
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data: